title = "Myelin"
description = "Designing the Future of Artifical Intelligence"

[[pages]]
path = "/team"
file = "team"
title = "Team"

[[pages]]
path = "/"
file = "index"

[[pages]]
path = "/vision"
file = "vision"
title = "Vision"
