title = "Myelin"
description = "Designing the Future of Artifical Intelligence"

[[pages]]
path = "/team"
file = "team"
title = "Team"

[[pages]]
file = "index"

[[pages]]
file = "_404"
title = "Page Not Found"

# [[pages]]
# path = "/vision"
# file = "vision"
# title = "Vision"


[additional]
website_repo = "MyelinAI/website"

[[additional.people]]
name = "Jan Nils Ferner"
username = "jnferner"
image_url = "https://avatars2.githubusercontent.com/u/9047632"

[[additional.people]]
name = "Ruben Schmidmeister"
username = "bash"
image_url = "https://avatars2.githubusercontent.com/u/4602612"

[[additional.people]]
name = "Mathias Fischler"
username = "Mafii"
image_url = "https://avatars2.githubusercontent.com/u/10061519"

[[additional.people]]
name = "Jeremy Stucki"
username = "jeremystucki"
image_url = "assets://jeremy"


[assets.style]
source = "sass/style.scss"

[assets.header_logo_2x]
source = "assets/header-logo-2x.png"

[assets.header_logo]
source = "assets/header-logo.png"

[assets.github_icon]
source = "assets/github-icon.svg"

[assets.jeremy]
source = "assets/jeremy.jpg"
