title = "Myelin"
description = "Designing the Future of Artifical Intelligence"
url_prefix = "https://www.myelin.ch"

[[pages]]
path = "/"
file = "index"

[[pages]]
file = "_404"
title = "Page Not Found"

[[pages]]
path = "/team"
file = "team"
title = "Team"

# [[pages]]
# path = "/vision"
# file = "vision"
# title = "Vision"

[additional]
website_repo = "myelin-ai/website"
blog_url = "https://blog.myelin.ch"

[[additional.people]]
name = "Jan Nils Ferner"
username = "jnferner"
image_url = "https://avatars2.githubusercontent.com/u/9047632"

[[additional.people]]
name = "Ruben Schmidmeister"
username = "bash"
image_url = "assets://ruben"

[[additional.people]]
name = "Mathias Fischler"
username = "Mafii"
image_url = "https://avatars2.githubusercontent.com/u/10061519"

[[additional.people]]
name = "Jeremy Stucki"
username = "jeremystucki"
image_url = "assets://jeremy"

[assets]
style = { source = "sass/style.scss" }
whitepaper_js = { source = "assets/whitepaper.js" }
header_logo = { source = "assets/header-logo.svg" }
github_icon = { source = "assets/github-icon.svg" }
jeremy = { source = "assets/jeremy.jpg" }
ruben = { source = "assets/ruben.jpg" }
wave_line = { source = "assets/wave-line.svg" }
